export { Point } from './primitives/Point'
export { Vector2 } from './primitives/Vector2'
export { Vector3 } from './primitives/Vector3'
export { Line } from './primitives/Line'
export { Segment } from './primitives/Segment'
export { Polygon } from './primitives/Polygon'
export { offsetSegment, offsetPolygon, wallOffsetPolygon } from './operations/Offset'
export { segmentIntersection, allSegmentIntersections, nearestPointOnSegment } from './operations/Intersect'
export { computeBoundingBox, expandBoundingBox, boundingBoxContains, boundingBoxIntersects, mergeBoundingBoxes } from './operations/BoundingBox'
export { SpatialGraph } from './graph/SpatialGraph'
export { FaceDetector } from './graph/FaceDetector'
export { AdjacencyMap } from './graph/AdjacencyMap'
export type { DetectedFace } from './graph/FaceDetector'
export type { GraphNode, GraphEdge } from './graph/SpatialGraph'
export type { RoomAdjacency } from './graph/AdjacencyMap'
